# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-01 07:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uloziste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Jm\xe9no')),
                ('birthNumber', models.CharField(max_length=10, verbose_name='Rodn\xe9 \u010d\xedslo')),
                ('diagnosis', models.CharField(max_length=100, verbose_name='Diagn\xf3za')),
                ('radAs', models.CharField(max_length=100, verbose_name='Rad. As.')),
                ('doctor', models.CharField(max_length=100, verbose_name='L\xe9ka\u0159')),
                ('resimulTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum a \u010das resimulace')),
                ('drawingTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum zakreslen\xed')),
                ('drawingDoctor', models.CharField(max_length=100, verbose_name='Zakreslen\xed stav/l\xe9ka\u0159')),
                ('planningTime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Datum pl\xe1nov\xe1n\xed')),
                ('planningDoctor', models.CharField(max_length=100, verbose_name='Zakreslen\xed stav/l\xe9ka\u0159')),
                ('ok1', models.CharField(max_length=100, verbose_name='Schv\xe1len\xed l\xe9ka\u0159 1')),
                ('ok2', models.CharField(max_length=100, verbose_name='Schv\xe1len\xed l\xe9ka\u0159 2')),
                ('tisk', models.BooleanField(default=True)),
            ],
        ),
    ]
