# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20160906_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloziste',
            name='drawingTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Zakreslen\xed'),
        ),
        migrations.AlterField(
            model_name='uloziste',
            name='pzn',
            field=models.TextField(blank=True, verbose_name='Pozn\xe1mka'),
        ),
        migrations.AlterField(
            model_name='uloziste',
            name='resimulTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 6, 7, 13, 23, 517929, tzinfo=utc), verbose_name='Resimulace'),
        ),
    ]
