# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 07:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20160906_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloziste',
            name='planningTime',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='Pl\xe1nov\xe1n\xed'),
        ),
        migrations.AlterField(
            model_name='uloziste',
            name='resimulTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 6, 7, 29, 56, 873423, tzinfo=utc), verbose_name='Resimulace'),
        ),
    ]
