# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 08:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20160906_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='uloziste',
            name='pznDisplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='uloziste',
            name='resimulTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Resimulace'),
        ),
    ]
