# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-06 09:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_uloziste_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uloziste',
            name='staff_member',
        ),
        migrations.AddField(
            model_name='uloziste',
            name='pznDisplay',
            field=models.BooleanField(default=False, verbose_name='Pzn'),
        ),
    ]
