# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_auto_20160911_2245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uloziste',
            name='resimulTime',
        ),
    ]
