# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_uloziste_resimultime'),
    ]

    operations = [
        migrations.AddField(
            model_name='uloziste',
            name='resimulTime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Resimulace'),
        ),
    ]
