# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 21:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_remove_uloziste_dr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uloziste',
            name='drawingTime',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Zakreslen\xed'),
        ),
        migrations.AlterField(
            model_name='uloziste',
            name='planningTime',
            field=models.DateField(blank=True, default=datetime.datetime.now, verbose_name='Pl\xe1nov\xe1n\xed'),
        ),
        migrations.AlterField(
            model_name='uloziste',
            name='resimulTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 11, 21, 43, 26, 573035, tzinfo=utc), verbose_name='Resimulace'),
        ),
    ]
